APP_URL= https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
BROWSER= chrome
UserName= Admin
Password= admin123
CHROME_DRIVER_LOCATION=C:\\Users\\Lakshmanan\\eclipse-workspace\\Job\\Drivers\\Chromedriver\\chromedriver.exe
FIREFOX_DRIVER_LOCATION=C:\Drivers\Firefoxdriver\geckodriver.exe
EDGE_DRIVER_LOCATION=C:\Drivers\Edgedriver\msedgedriver.exe
OPERA_DRIVER_LOCATION=C:\Drivers\Operadriver\operadriver_win64\operadriver.exe